### ISSUE TITLE
Quotation marks aren't properly highlighted in list items

### ISSUE THREAD

**Issue by rafaeln** [vim-pandoc/vim-pandoc-syntax#114]
You can see that in the screenshot below.

![screenshot from 2015-01-12 10 17 24](https://cloud.githubusercontent.com/assets/2940362/5707221/46344288-9a44-11e4-880e-ca69ed7b0d02.png)

**Comment by fmoralesc** [comment]
Thanks. Just fixed in master.

**Comment by rafaeln** [comment]
It is still not working perfectly. Quotes are only properly highlighted in non-initial paragraphs of list items. If the paragraph begins with the quotes, though, they aren't highlighted, and it also breaks formatting for any further paragraphs. Interestingly, highlighting also doesn't work for italics if a paragraph begins with it, and this will also break highlighting in further paragraphs. See the screenshot below.  

![screenshot from 2015-01-12 11 13 10](https://cloud.githubusercontent.com/assets/2940362/5708160/05d0bc46-9a4c-11e4-91ab-e76750fb7f0e.png)

**Comment by fmoralesc** [comment]
It seems that I made an oversight about unordered list items, should be fixed now.

![captura de pantalla de 2015-01-12 15 33 43](https://cloud.githubusercontent.com/assets/221465/5708499/6906f16c-9a70-11e4-939d-558ebd317a02.png)

**Comment by rafaeln** [comment]
Hum, I've just pulled commit e63f7350b25d3b59e8b67c08ef9e76c61ec14b77 and it doesn't seem to solve the issue for me. Can you confirm this is the commit that is supposed to fix it so that I can proceed to test this in a cleaner environment?

![screenshot from 2015-01-12 11 40 18](https://cloud.githubusercontent.com/assets/2940362/5708640/17bc9f02-9a50-11e4-9714-d6ad716b44f0.png)

**Comment by fmoralesc** [comment]
Indeed, that is the commit. Lines 451-452 of `syntax/pandoc.vim` should be:

~~~ vim
call s:WithConceal("quotes", 'syn match pandocBeginQuote /"\</  containedin=pandocEmphasis,pandocStrong,pandocListItem,pandocListItemContinuation,pandocUListItem display', 'conceal cchar=“')
call s:WithConceal("quotes", 'syn match pandocEndQuote /\(\>[[:punct:]]*\)\@<="[[:blank:][:punct:]\n]\@=/  containedin=pandocEmphasis,pandocStrong,pandocUListItem,pandocListItem,pandocListItemContinuation display', 'conceal cchar=”')
~~~

**Comment by rafaeln** [comment]
Hum... We am indeed using the same commit, with lines 451-452 matching what you gave above.

Even using the following minimal .vimrc, which deactivates all other plugins in my system, I still get the same result (screenshot follows)

~~~vim
scriptencoding utf-8
set encoding=utf-8

filetype plugin on

let g:pathogen_disabled = [ 'flappyvird-vim', 'goyo.vim', 'gundo', 'LaTeX-Box', 'python-mode', 'repmo.vim', 'seoul256.vim', 'smartpairs.vim', 'ultisnips', 'vim-abolish', 'vim-characterize', 'vim-colors-solarized', 'vim-commentary', 'vim-easy-align', 'vim-eunuch', 'vim-fugitive', 'vim-gitgutter', 'vim-markdown', 'vim-obsession', 'vim-repeat', 'vim-scriptease', 'vim-sensible', 'vim-snippets', 'vim-surround', 'vim-tmux-navigator', 'vim-unimpaired', 'vim-vinegar', 'vim-visual-star-search', 'vim-yankstack', 'Zenburn']

execute pathogen#infect()
~~~

![image](https://cloud.githubusercontent.com/assets/2940362/5709036/7d1788e6-9a53-11e4-97f5-6f89435cee3e.png)

**Comment by fmoralesc** [comment]
What is the output of 
~~~ vim
echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
~~~
when the cursor is over the `"` in `"quotes"` (line 14) and `_` in `_italics_` (line 13). It should be:

     ["pandocBeginQuote"]

and 

    ["pandocEmphasis", "Operator"]

I'm kinda clueless. What vim version are you using?

**Comment by rafaeln** [comment]
The output is, `['pandocCodeblock']` whether the cursor is on the `"` in `"quotes"` (line 14) or on the `_` in `_italics_` (line 13).

I'm using

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
    Included patches: 1-52
    Modified by pkg-vim-maintainers@lists.alioth.debian.org
    Compiled by buildd@

Here are the output of that command in other positions:

![image](https://cloud.githubusercontent.com/assets/2940362/5709947/4810a3c8-9a5b-11e4-8e37-c89837dc8205.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709952/6021369e-9a5b-11e4-8b38-65dd8c8d0f53.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709958/750c769a-9a5b-11e4-9d5a-d63f69fd9e0b.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709960/839a29e6-9a5b-11e4-94c9-bd66d092a23e.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709968/91ed9636-9a5b-11e4-9cbf-e51b2c2925a2.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709974/9ff965a2-9a5b-11e4-90bf-5e296b8b8d54.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709982/af525554-9a5b-11e4-8773-1f9b8cee3ee9.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709985/bd7141cc-9a5b-11e4-9873-3a48645733dc.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5709995/ceb46fe0-9a5b-11e4-825c-06f2252f352b.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5710006/de69a658-9a5b-11e4-8298-baae368f040b.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5710022/ed0f81e6-9a5b-11e4-81f7-31d7cf81e375.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5710032/00b5ebcc-9a5c-11e4-928e-15c0a7c764a5.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5710038/11632836-9a5c-11e4-9c3d-70c9327eb646.png)

![image](https://cloud.githubusercontent.com/assets/2940362/5710040/1f4413ac-9a5c-11e4-8941-6b143a658840.png)

**Comment by fmoralesc** [comment]
Thanks, I see now what the problem is. I was testing over 3 spaces on the indent, so my tests were skewed. I just pushed a partial fix. It still won't be correct when the line begins with `_` though (I'm not sure why).

**Comment by rafaeln** [comment]
It does seem to work, though, when the line begins with `_` (and I've taken this screenshot with my regular `.vimrc`)

![image](https://cloud.githubusercontent.com/assets/2940362/5711345/f18fd6b6-9a66-11e4-99e0-0a933c1fe7f0.png)

**Comment by fmoralesc** [comment]
Weirdness all around, I guess. Perhaps there are further differences between our text samples. Mine was 
~~~

"quotes"

 "quotes"

 * item item "quotes" *italics*

    something "quotes"

    something *italics*
 
    _italics_

    something "quotes"

 * second item "quotes" *italics*

    something "quotes"

    something *italics*

    "quotes"

    something _italics_

~~~

**Comment by rafaeln** [comment]
Weirdness all around indeed. I copy-pasted your text sample into a vim buffer and got correct highlighting throughout. My text sample goes below

````text

"quotes"

  "quotes"

  * first item "quotes" _italics_

    something "quotes"

    something _italics_

    _italics_

    something "quotes"

  * first item "quotes" _italics_

    something "quotes"

    something _italics_

    "quotes"

    something _italics_
````

**Comment by fmoralesc** [comment]
It seems to work fine in both cases now for me. I guess I had some invalid syntax rule cached, or something like that. I'll close the issue before it jinxes itself.
